# Generated by Django 4.1.6 on 2023-05-08 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_plane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=30)),
                ('noOfPassengers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('noOfAvailableSeats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ETA', models.DateTimeField()),
                ('ETD', models.DateTimeField()),
                ('flightDuration', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_location', to='pages.location')),
                ('planeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.plane')),
                ('startLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='pages.location')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfSeatsBooked', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('confirmedStatus', models.BooleanField(default=False)),
                ('timeStarted', models.DateTimeField()),
                ('flightID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.flight')),
                ('passengerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceOfEconomy', models.DecimalField(decimal_places=2, max_digits=7)),
                ('priceOfBusiness', models.DecimalField(decimal_places=2, max_digits=7)),
                ('priceOfFirstClass', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(max_length=3)),
                ('flightID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.flight')),
            ],
        ),
    ]
