# Generated by Django 4.1.6 on 2023-05-10 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_reservation_noofseatsbooked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='ETA',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='ETD',
        ),
        migrations.RemoveField(
            model_name='price',
            name='flightID',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrivalDate',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=datetime.time(15, 3, 0, 86816)),
        ),
        migrations.AddField(
            model_name='flight',
            name='departureDate',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AddField(
            model_name='flight',
            name='departureTime',
            field=models.TimeField(default=datetime.time(15, 3, 0, 86816)),
        ),
        migrations.AddField(
            model_name='flight',
            name='priceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.price'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flightDuration',
            field=models.DurationField(),
        ),
    ]
