# Generated by Django 4.1.6 on 2023-05-10 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_flight_arrivaltime_alter_flight_departuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=datetime.time(15, 38, 21, 722680)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureTime',
            field=models.TimeField(default=datetime.time(15, 38, 21, 722680)),
        ),
    ]
