# Generated by Django 4.1.6 on 2023-05-11 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_flight_arrivaltime_alter_flight_departuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrivalDate',
            field=models.DateField(default=datetime.date(2023, 5, 11)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=datetime.time(11, 23, 29, 234126)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureDate',
            field=models.DateField(default=datetime.date(2023, 5, 11)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureTime',
            field=models.TimeField(default=datetime.time(11, 23, 29, 234126)),
        ),
    ]
