# Generated by Django 4.1.6 on 2023-05-11 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_flight_arrivaldate_alter_flight_arrivaltime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=datetime.time(11, 23, 35, 836791)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureTime',
            field=models.TimeField(default=datetime.time(11, 23, 35, 836791)),
        ),
    ]
