# Generated by Django 4.1.6 on 2023-05-11 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_flight_arrivaltime_alter_flight_departuretime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=datetime.time(11, 33, 11, 469646)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureTime',
            field=models.TimeField(default=datetime.time(11, 33, 11, 469646)),
        ),
    ]
