# Generated by Django 4.1.6 on 2023-05-11 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_flight_arrivaltime_alter_flight_departuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=datetime.time(13, 12, 4, 50613)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureTime',
            field=models.TimeField(default=datetime.time(13, 12, 4, 50613)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passengerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.passenger'),
        ),
    ]
