# Generated by Django 4.1.6 on 2023-05-11 14:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_flight_arrivaltime_alter_flight_departuretime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='noOfAvailableSeats',
        ),
        migrations.AddField(
            model_name='flight',
            name='availableSeatsBusiness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='availableSeatsEconomy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='availableSeatsFirstClass',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=datetime.time(14, 34, 28, 128081)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureTime',
            field=models.TimeField(default=datetime.time(14, 34, 28, 128081)),
        ),
    ]
