# Generated by Django 4.1.6 on 2023-05-11 15:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_flight_noofavailableseats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='totalAvailabeSeats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrivalTime',
            field=models.TimeField(default=datetime.time(15, 17, 36, 231324)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureTime',
            field=models.TimeField(default=datetime.time(15, 17, 36, 231324)),
        ),
    ]
